Public Class DataType.Java{
    Public static void main(string[]args){
        int number = 1234567890;
        String stringvariable ="Hello";
Char varible ='h';
Short shortvariable = 12345;
Long longvariable = 123456789000L;
byte bytevarible = (byte)3444;
// Flooting-Point
float temprature = 36.667f;
double gravity =  9.80665;
//Integers
long worldPop = 8_000_000_000L;
//Bases
int binary=0b1010;
int octal=012;
int hex=0*A;
//other types
byte small=(byte)127;
char grade='A';
boolean isValid=true;
String massage="Literals demo";
System.out.println("int says: I can hold big number" + number );
System.out.println("string says": +stringvariable+ "is my favorite word")

    }
}